In [1]:
import numpy as np
np.empty((3,3,3))

array([[[1.11364512e-311, 1.11360937e-311, 4.64501053e+151],
        [5.56206167e+180, 2.85427980e-109, 7.68233221e-010],
        [5.34083717e+228, 5.02383426e+223, 8.03704345e-095]],

       [[5.50495710e-095, 8.03408340e-095, 1.95575364e-109],
        [1.35717430e+131, 6.40695294e+029, 2.65862908e-260],
        [2.17237845e-153, 1.69201561e+190, 7.04134408e-009]],

       [[5.60578750e+199, 4.14825036e-114, 4.53541174e-057],
        [1.03063392e-113, 1.05894612e-153, 6.03134498e-154],
        [1.72221190e+097, 1.16304910e+214, 3.16285926e-294]]])

In [ ]:

2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
np.diag(1+np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
4. Normalize a 5x5 random matrix

In [4]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.71818954 0.83346281 0.06507589 0.76200484 0.73276275]
 [0.90866243 0.43708286 0.44985479 0.86705326 0.58216862]
 [0.21025827 0.37438335 0.0882121  0.88700362 0.89200643]
 [0.18877369 0.11488755 0.18201812 0.71790933 0.51712984]
 [0.88116371 0.68176501 0.39588704 0.65872239 0.6610211 ]]
After normalization:
[[0.77421062 0.91085725 0.         0.82614992 0.79148591]
 [1.         0.44098258 0.45612262 0.95067588 0.6129694 ]
 [0.17210136 0.36665766 0.02742601 0.97432532 0.98025573]
 [0.14663321 0.05904748 0.13862506 0.77387845 0.53587147]
 [0.96740262 0.73103243 0.39214845 0.70371737 0.70644229]]


In [ ]:
5. How to find common values between two arrays?

In [5]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

np.intersect1d(a, b)

array([2, 4, 7, 9])

In [ ]:
6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yest = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tom  = np.datetime64('today') + np.timedelta64(1)
print(yest, today, tom)

2020-08-05 2020-08-06 2020-08-07


In [ ]:

7. Consider two random array A and B, check if they are equal

In [7]:
a=np.random.random((3,3))
b=np.random.random((3,3))
if a.all()==b.all():
    print('They are equal')
else:
    print('They are not equal')

They are equal


In [ ]:
8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
a = np.random.rand(10)
a[a.argmax()] = 0
a

array([0.34502471, 0.43314413, 0.49029503, 0.85669067, 0.06406882,
       0.35464058, 0.56493779, 0.48525843, 0.31022305, 0.        ])

In [ ]:
9. How to print all the values of an array?¶

In [9]:
a=np.random.random((2,2))
print(a)

[[0.90501425 0.53416858]
 [0.05639722 0.81250753]]


In [ ]:
10.Subtract the mean of each row of a matrix

In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1=a[0].mean()
m2=a[1].mean()
m3=a[2].mean()
print(m1-m2-m3)

-11.0


In [ ]:
11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
a = np.ones(5)
b = np.random.randint(0, len(a), 10)
a += np.bincount(b, minlength = len(a))
a

array([4., 2., 2., 3., 4.])

In [ ]:
12.How to get the diagonal of a dot product?

In [12]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", a, b)

array([ 9, 77, 98])

In [ ]:
13.How to find the most frequent value in an array?

In [13]:
a = np.random.randint(0,10,20)
print(a)
max(set(a), key = list(a).count)

[2 6 2 4 4 9 0 1 4 1 8 5 9 2 2 2 6 2 0 7]


2

In [ ]:
14.How to get the n largest values of an array

In [14]:
a=np.random.random((3,3))
print(a.max())

0.9354978300278173


In [ ]:
15.How to create a record array from a regular array?

In [15]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record


[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])